apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-rxsx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-rxsx
    app.kubernetes.io/part-of: tkrw-pr714-0075-0045-app
  name: devfile-sample-rxsx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-rxsx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-rxsx
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0045-tenant/tkrw-pr714-0075-0045-app/devfile-sample-rxsx@sha256:dbc829df77c5dd7b6f8f3233269737615d3f899811657a2c892f08b569a92ad8
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
